"""add feature authorization

Revision ID: 56fb89c13e25
Revises: c3ddf61c1ae1
Create Date: 2024-07-20 20:15:09.537468

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56fb89c13e25"
down_revision: Union[str, None] = "c3ddf61c1ae1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authorized_features",
        sa.Column("id", sa.String(length=21), nullable=False),
        sa.Column("create_dt", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("update_dt", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("user_id", sa.String(length=21), nullable=False),
        sa.Column("feature", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_authorized_features_id"), "authorized_features", ["id"], unique=True)
    op.create_index(op.f("ix_authorized_features_user_id"), "authorized_features", ["user_id"], unique=False)
    op.add_column("user", sa.Column("type", sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "type")
    op.drop_index(op.f("ix_authorized_features_user_id"), table_name="authorized_features")
    op.drop_index(op.f("ix_authorized_features_id"), table_name="authorized_features")
    op.drop_table("authorized_features")
    # ### end Alembic commands ###
